#!/bin/tcsh
setenv CXXFLAGS -O4
setenv ARCH i386-linux-opt

g++ -m32 -O4 -Irelease -Wall -c myana_cspad-gjw.cc
g++ -m32 -O4 -Irelease -Wall -c CspadTemp.cc
g++ -m32 -O4 -Irelease -Wall -c CspadGeometry.cc
g++ -m32 -O4 -Irelease -Wall -c CspadCorrector.cc
g++ -m32 -O4 ../main.o ../XtcRun.o myana_cspad-gjw.o CspadCorrector.o CspadGeometry.o CspadTemp.o -Wl,-rpath=./release/build/pdsdata/lib/i386-linux-opt/ -Lrelease/build/pdsdata/lib/i386-linux-opt/ -l acqdata -l bld -l xtcdata -l opal1kdata -l camdata -l pnccddata -l controldata -lipimbdata -lprincetondata -levrdata -lencoderdata -llusidata -lcspaddata -o myana_cspad-gjw
