#!/bin/tcsh
setenv CXXFLAGS -O4
setenv ARCH x86_64-linux
setenv HDF5DIR /reg/neh/home/barty/hdf5

set PDSLIBS='-l acqdata -l bld -l xtcdata -l opal1kdata -l camdata -l pnccddata -l controldata -lipimbdata -lprincetondata -levrdata -lencoderdata -llusidata -lcspaddata'

g++ -O4 -I../release -I$HDF5DIR/include -Wall -c myana_cspad-gjw.cc
g++ -O4 -I../release -Wall -c CspadTemp.cc
g++ -O4 -I../release -Wall -c CspadGeometry.cc
g++ -O4 -I../release -Wall -c CspadCorrector.cc
g++ -O4 ../myana/main.o ../myana/XtcRun.o myana_cspad-gjw.o CspadCorrector.o CspadGeometry.o CspadTemp.o -Wl,-rpath=../release/build/pdsdata/lib/$ARCH/ -L../release/build/pdsdata/lib/$ARCH/ $PDSLIBS -lhdf5 -I$HDF5DIR/include -L$HDF5DIR/lib -o myana_cspad-gjw
