#!/bin/bash

# Sample build file for libcheetah
# will need to be modified for each person (or the script improved)

export HDF5DIR=/reg/neh/home1/barty/hdf5
export CHEETAHDIR=/reg/neh/home1/barty/c/cheetah

export LD_LIBRARY_PATH="/reg/neh/home1/barty/lib:/reg/neh/home1/barty/c/cheetah/source/lcls/myana/release/build/pdsdata/lib/x86_64-linux"
export LD_RUN_PATH="/reg/neh/home1/barty/lib:/reg/neh/home1/barty/c/cheetah/source/lcls/myana/release/build/pdsdata/lib/x86_64-linux"

cd source
#make cheetah
make libcheetah

#cp cheetah /reg/d/psdm/cxi/cxi54312/scratch/programs/bin/cheetah-rick
cp cheetah /reg/neh/home1/barty/bin

rm /reg/neh/home1/barty/lib/libcheetah*
rm /reg/neh/home1/barty/c/cheetah/lib/libcheetah*

cp libcheetah.so.* /reg/neh/home1/barty/lib
cp libcheetah.so.* /reg/neh/home1/barty/c/cheetah/lib
cp /reg/neh/home1/barty/lib/libcheetah.so.1.0 /reg/neh/home1/barty/lib/libcheetah.so
cp /reg/neh/home1/barty/lib/libcheetah.so.1.0 /reg/neh/home1/barty/lib/libcheetah.so.1
cp /reg/neh/home1/barty/c/cheetah/lib/libcheetah.so.1.0 /reg/neh/home1/barty/c/cheetah/lib/libcheetah.so
cp /reg/neh/home1/barty/c/cheetah/lib/libcheetah.so.1.0 /reg/neh/home1/barty/c/cheetah/lib/libcheetah.so.1
