#!/bin/tcsh
# $Id: comp,v 1.18 2010/10/21 21:51:19 weaver Exp $
#setenv CXXFLAGS -g
#setenv ARCH i386-linux-dbg
setenv CXXFLAGS -O4
setenv ARCH i386-linux-opt
set PDSLIBS='-l acqdata -l bld -l xtcdata -l opal1kdata -l camdata -l pnccddata -l controldata -lipimbdata -lprincetondata -levrdata -lencoderdata -llusidata -lcspaddata'
set OBJFILES='main.o XtcRun.o'

g++ -m32 $CXXFLAGS -Irelease -Wall -c XtcRun.cc
g++ -m32 $CXXFLAGS -Irelease -Wall -c main.cc
#g++ -m32 $CXXFLAGS -Irelease -Wall -c myana.cc
g++ -m32 $CXXFLAGS -Irelease -Wall -c myana_morefeatures.cc
#g++ -m32 $CXXFLAGS $OBJFILES myana.o -Wl,-rpath=./release/build/pdsdata/lib/$ARCH/ -Lrelease/build/pdsdata/lib/$ARCH/ $PDSLIBS -o myana
g++ -m32 $CXXFLAGS $OBJFILES myana_morefeatures.o -Wl,-rpath=./release/build/pdsdata/lib/$ARCH/ -Lrelease/build/pdsdata/lib/$ARCH/ $PDSLIBS -o myana_morefeatures
