#!/bin/tcsh

# Script for simplifying the conversion of XTC files to HDF5
#	Syntax:
#	> crystfinder r0003 crystfinder.ini
#

setenv XTCDIR '/cfel/rawdata/LCLS/LCLS-201102/xtc'
setenv H5DIR '/cfel/tempdata/LCLS/LCLS-201102/cleaned_hdf5'
setenv LOGDIR '/cfel/tempdata/LCLS/LCLS-201102/cleaned_hdf5/logs'
setenv INIDIR '/cfel/tempdata/LCLS/LCLS-201102/scripts'
setenv COMMAND '/cfel/common/bin/cheetah'


# All OK?
echo $1
echo $2


# Has an '.ini' file been specified on the commanbd line?
if ($2 != '') then
	setenv INIFILE $2
else
	setenv INIFILE 'cspad-cryst.ini'
endif


# Create directory for this data set
echo 'Creating directory'
if( ! -e $H5DIR/$1) then
	mkdir $H5DIR/$1
endif

# Move to HDF5 directory
cd $H5DIR/$1

# Clean out old HDF5 files
echo 'Removing existing HDF5 files'
rm -f *.h5


# Create configuration files
echo 'Creating configuration files'
cp $INIDIR/$INIFILE cspad-cryst.ini
ls $XTCDIR/*$1* > files.txt

# make everything group editable!
chmod -R g+w $H5DIR/$1

# Spawn cspad_cryst for file conversion
echo "$COMMAND -l files.txt >& $LOGDIR/$1.log" 
$COMMAND -l files.txt >& $LOGDIR/$1.log 
#$COMMAND -l files.txt 
#gdb $COMMAND -l files.txt 

# make everything group editable!
chmod -R g+w $H5DIR/$1

#
echo 'crystfinder has finished'
