#!/bin/bash
#export CXXFLAGS=-O4
export ARCH=x86_64-linux-dbg
#release/build/pdsdata/lib/i386-linux-opt
export ROOTSYS=/reg/g/pcds/package/root
export PDSLIBS='-l acqdata -l bld -l xtcdata -l opal1kdata -l camdata -l pnccddata -l controldata -lipimbdata -lprincetondata -levrdata -lencoderdata -llusidata -lcspaddata'
export OBJFILES='main.o XtcRun.o'

prog="myana_monitors"

g++ $CXXFLAGS -Irelease -Wall `$ROOTSYS/bin/root-config --cflags` -c XtcRun.cc
g++ $CXXFLAGS -Irelease -Wall `$ROOTSYS/bin/root-config --cflags` -c main.cc
#g++ $CXXFLAGS -Irelease -Wall `$ROOTSYS/bin/root-config --cflags` -c myana.cc
g++ $CXXFLAGS -Irelease -Wall `$ROOTSYS/bin/root-config --cflags` -c $prog.cc
#g++ $CXXFLAGS $OBJFILES myana.o -Wl,-rpath=$ROOTSYS/lib:./release/build/pdsdata/lib/$ARCH/ `$ROOTSYS/bin/root-config --libs` -Lrelease/build/pdsdata/lib/$ARCH/ $PDSLIBS -o myana
#g++ $CXXFLAGS $OBJFILES myana_morefeatures.o -Wl,-rpath=$ROOTSYS/lib:./release/build/pdsdata/lib/$ARCH/ `$ROOTSYS/bin/root-config --libs` -Lrelease/build/pdsdata/lib/$ARCH/ $PDSLIBS -o myana_morefeatures
g++ $CXXFLAGS $OBJFILES $prog.o -Wl,-rpath=$ROOTSYS/lib:./release/build/pdsdata/lib/$ARCH/ `$ROOTSYS/bin/root-config --libs` -Lrelease/build/pdsdata/lib/$ARCH/ $PDSLIBS -o $prog
