#!/bin/tcsh


switch ($1)

	case heidelberg
	#rsync -av cass barty@lfs3.mpi-hd.mpg.de:oldcass/mimicass
	breaksw
	
	case mms1:
	#rsync -av cass barty@mms1.desy.de:local/cass/mimicass
	breaksw
	
	case psexport:
	#rsync -av --delete-after --exclude '.git' . barty@psexport.slac.stanford.edu:cspad
	#rsync -av --delete-after --exclude '*.o' --exclude 'release' --exclude '.git' . barty@psexport.slac.stanford.edu:cspad
	rsync -av --delete-after --exclude 'release' --exclude '.git' . barty@psexport.slac.stanford.edu:cspad
	breaksw
	

endsw
