#!/bin/tcsh


switch ($1)

	case heidelberg
	#rsync -av cass barty@lfs3.mpi-hd.mpg.de:oldcass/mimicass
	breaksw
	
	case mms1:
	#rsync -av cass barty@mms1.desy.de:local/cass/mimicass
	breaksw
	
	case cfelsgi:
	rsync -av --exclude 'build' --exclude '.git' . barty@cfelsgi.desy.de:local/c/cheetah/
	breaksw
	
	case psexport:
	rsync -av *.cpp *.h  barty@psexport.slac.stanford.edu:c/cheetah/
	#rsync -av --exclude 'release' --exclude 'build' --exclude '.git' --exclude '*.o' --exclude Makefile . barty@psexport.slac.stanford.edu:c/cheetah/
	breaksw
	

endsw
