#!/bin/tcsh
# $Id: comp,v 1.26 2012/05/04 21:17:24 tomytsai Exp $
setenv CXXFLAGS -g
#setenv ARCH i386-linux-dbg
#setenv CXXFLAGS -O4
setenv ARCH i386-linux-opt
setenv ROOTSYS /reg/g/pcds/package/root
set PDSLIBS='-l acqdata -l bld -l xtcdata -l opal1kdata -l camdata -l pnccddata -l controldata -lipimbdata -lprincetondata -levrdata -lencoderdata -lgsc16aidata -llusidata -lcspaddata -lindexdata -lanadata -lcspad2x2data -lphasicsdata -ltimepixdata -loceanopticsdata -lflidata'
set OBJFILES='main.o'

g++ $CXXFLAGS -Irelease -Wall -c main.cc
g++ $CXXFLAGS -Irelease -Wall -c myana.cc
#g++ $CXXFLAGS -Irelease -Wall -c myana_morefeatures.cc
g++ $CXXFLAGS $OBJFILES -lpthread myana.o -Wl,-rpath=$PWD/release/build/pdsdata/lib/$ARCH/ -Lrelease/build/pdsdata/lib/$ARCH/ $PDSLIBS -o myana
#g++ $CXXFLAGS $OBJFILES -lpthread myana_morefeatures.o -Wl,-rpath=$PWD/release/build/pdsdata/lib/$ARCH/ -Lrelease/build/pdsdata/lib/$ARCH/ $PDSLIBS -o myana_morefeatures


