#!/bin/tcsh
# $Id: comp_pnccd,v 1.3 2011/05/11 01:06:45 caf Exp $
#setenv CXXFLAGS -g
#setenv ARCH i386-linux-dbg
setenv CXXFLAGS -O4
setenv ARCH i386-linux-opt
setenv ROOTSYS /reg/g/pcds/package/root
set PDSLIBS='-l acqdata -l bld -l xtcdata -l opal1kdata -l camdata -l pnccddata -l controldata -lipimbdata -lprincetondata -levrdata -lencoderdata -llusidata -lcspaddata'
set OBJFILES='main.o XtcRun.o'

g++ -m32 $CXXFLAGS -I../release -Wall `$ROOTSYS/bin/root-config --cflags` -c ../XtcRun.cc
g++ -m32 $CXXFLAGS -I../release -Wall `$ROOTSYS/bin/root-config --cflags` -c ../main.cc
g++ -m32 $CXXFLAGS -I../release -Wall `$ROOTSYS/bin/root-config --cflags` -c myana_pnccd.cc
g++ -m32 $CXXFLAGS -I../release -Wall `$ROOTSYS/bin/root-config --cflags` -c PnccdCorrector.cc
g++ -m32 $CXXFLAGS $OBJFILES myana_pnccd.o PnccdCorrector.o -Wl,-rpath=$ROOTSYS/lib:../release/build/pdsdata/lib/$ARCH/ `$ROOTSYS/bin/root-config --libs` -L../release/build/pdsdata/lib/$ARCH/ $PDSLIBS -o myana_pnccd
