# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cxiview.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1400, 1200)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout4 = QtGui.QHBoxLayout()
        self.horizontalLayout4.setObjectName(_fromUtf8("horizontalLayout4"))
        self.verticalLayout.addLayout(self.horizontalLayout4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.refreshfilesPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshfilesPushButton.sizePolicy().hasHeightForWidth())
        self.refreshfilesPushButton.setSizePolicy(sizePolicy)
        self.refreshfilesPushButton.setMaximumSize(QtCore.QSize(100, 32))
        self.refreshfilesPushButton.setObjectName(_fromUtf8("refreshfilesPushButton"))
        self.horizontalLayout.addWidget(self.refreshfilesPushButton)
        self.previousPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousPushButton.sizePolicy().hasHeightForWidth())
        self.previousPushButton.setSizePolicy(sizePolicy)
        self.previousPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.previousPushButton.setObjectName(_fromUtf8("previousPushButton"))
        self.horizontalLayout.addWidget(self.previousPushButton)
        self.nextPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextPushButton.sizePolicy().hasHeightForWidth())
        self.nextPushButton.setSizePolicy(sizePolicy)
        self.nextPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nextPushButton.setObjectName(_fromUtf8("nextPushButton"))
        self.horizontalLayout.addWidget(self.nextPushButton)
        self.playPushButton = QtGui.QPushButton(self.centralwidget)
        self.playPushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playPushButton.sizePolicy().hasHeightForWidth())
        self.playPushButton.setSizePolicy(sizePolicy)
        self.playPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.playPushButton.setObjectName(_fromUtf8("playPushButton"))
        self.horizontalLayout.addWidget(self.playPushButton)
        self.randomPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randomPushButton.sizePolicy().hasHeightForWidth())
        self.randomPushButton.setSizePolicy(sizePolicy)
        self.randomPushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.randomPushButton.setObjectName(_fromUtf8("randomPushButton"))
        self.horizontalLayout.addWidget(self.randomPushButton)
        self.shufflePushButton = QtGui.QPushButton(self.centralwidget)
        self.shufflePushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shufflePushButton.sizePolicy().hasHeightForWidth())
        self.shufflePushButton.setSizePolicy(sizePolicy)
        self.shufflePushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.shufflePushButton.setObjectName(_fromUtf8("shufflePushButton"))
        self.horizontalLayout.addWidget(self.shufflePushButton)
        self.jumpToLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jumpToLabel.sizePolicy().hasHeightForWidth())
        self.jumpToLabel.setSizePolicy(sizePolicy)
        self.jumpToLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.jumpToLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jumpToLabel.setObjectName(_fromUtf8("jumpToLabel"))
        self.horizontalLayout.addWidget(self.jumpToLabel)
        self.jumpToLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jumpToLineEdit.sizePolicy().hasHeightForWidth())
        self.jumpToLineEdit.setSizePolicy(sizePolicy)
        self.jumpToLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.jumpToLineEdit.setObjectName(_fromUtf8("jumpToLineEdit"))
        self.horizontalLayout.addWidget(self.jumpToLineEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.imageView = ImageView(self.centralwidget)
        self.imageView.setEnabled(True)
        self.imageView.setObjectName(_fromUtf8("imageView"))
        self.verticalLayout.addWidget(self.imageView)
        self.horizontalLayout2 = QtGui.QHBoxLayout()
        self.horizontalLayout2.setObjectName(_fromUtf8("horizontalLayout2"))
        self.horizontalLayout3 = QtGui.QHBoxLayout()
        self.horizontalLayout3.setObjectName(_fromUtf8("horizontalLayout3"))
        self.statusBar = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setMinimumSize(QtCore.QSize(500, 0))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.horizontalLayout3.addWidget(self.statusBar)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout3.addItem(spacerItem1)
        self.foundPeaksCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.foundPeaksCheckBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.foundPeaksCheckBox.setObjectName(_fromUtf8("foundPeaksCheckBox"))
        self.horizontalLayout3.addWidget(self.foundPeaksCheckBox)
        self.predictedPeaksCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.predictedPeaksCheckBox.setEnabled(False)
        self.predictedPeaksCheckBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.predictedPeaksCheckBox.setObjectName(_fromUtf8("predictedPeaksCheckBox"))
        self.horizontalLayout3.addWidget(self.predictedPeaksCheckBox)
        self.masksCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.masksCheckBox.setEnabled(True)
        self.masksCheckBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.masksCheckBox.setObjectName(_fromUtf8("masksCheckBox"))
        self.horizontalLayout3.addWidget(self.masksCheckBox)
        self.resolutionCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.resolutionCheckBox.setEnabled(True)
        self.resolutionCheckBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.resolutionCheckBox.setObjectName(_fromUtf8("resolutionCheckBox"))
        self.horizontalLayout3.addWidget(self.resolutionCheckBox)
        self.horizontalLayout2.addLayout(self.horizontalLayout3)
        self.verticalLayout.addLayout(self.horizontalLayout2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1400, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuColours = QtGui.QMenu(self.menuBar)
        self.menuColours.setObjectName(_fromUtf8("menuColours"))
        self.menuAnalysis = QtGui.QMenu(self.menuBar)
        self.menuAnalysis.setObjectName(_fromUtf8("menuAnalysis"))
        self.menuCXI = QtGui.QMenu(self.menuBar)
        self.menuCXI.setObjectName(_fromUtf8("menuCXI"))
        self.menuCrystals = QtGui.QMenu(self.menuBar)
        self.menuCrystals.setObjectName(_fromUtf8("menuCrystals"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave_data = QtGui.QAction(MainWindow)
        self.actionSave_data.setObjectName(_fromUtf8("actionSave_data"))
        self.actionSave_image = QtGui.QAction(MainWindow)
        self.actionSave_image.setObjectName(_fromUtf8("actionSave_image"))
        self.actionLoad_geometry = QtGui.QAction(MainWindow)
        self.actionLoad_geometry.setObjectName(_fromUtf8("actionLoad_geometry"))
        self.actionRefresh_file_list = QtGui.QAction(MainWindow)
        self.actionRefresh_file_list.setObjectName(_fromUtf8("actionRefresh_file_list"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionDefault_crystal_display_settings = QtGui.QAction(MainWindow)
        self.actionDefault_crystal_display_settings.setObjectName(_fromUtf8("actionDefault_crystal_display_settings"))
        self.actionCircle_Cheetah_peaks = QtGui.QAction(MainWindow)
        self.actionCircle_Cheetah_peaks.setObjectName(_fromUtf8("actionCircle_Cheetah_peaks"))
        self.actionDefault_particle_display_settings = QtGui.QAction(MainWindow)
        self.actionDefault_particle_display_settings.setObjectName(_fromUtf8("actionDefault_particle_display_settings"))
        self.actionHistogram_clip = QtGui.QAction(MainWindow)
        self.actionHistogram_clip.setCheckable(True)
        self.actionHistogram_clip.setChecked(True)
        self.actionHistogram_clip.setObjectName(_fromUtf8("actionHistogram_clip"))
        self.actionAuto_scale_levels = QtGui.QAction(MainWindow)
        self.actionAuto_scale_levels.setCheckable(True)
        self.actionAuto_scale_levels.setChecked(True)
        self.actionAuto_scale_levels.setObjectName(_fromUtf8("actionAuto_scale_levels"))
        self.actionAutoscale = QtGui.QAction(MainWindow)
        self.actionAutoscale.setCheckable(True)
        self.actionAutoscale.setChecked(True)
        self.actionAutoscale.setObjectName(_fromUtf8("actionAutoscale"))
        self.menu_view_photonconversion = QtGui.QAction(MainWindow)
        self.menu_view_photonconversion.setObjectName(_fromUtf8("menu_view_photonconversion"))
        self.menuFile.addAction(self.actionRefresh_file_list)
        self.menuFile.addAction(self.actionLoad_geometry)
        self.menuFile.addAction(self.actionSave_image)
        self.menuFile.addAction(self.actionSave_data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuCXI.addAction(self.actionDefault_particle_display_settings)
        self.menuCrystals.addAction(self.actionDefault_crystal_display_settings)
        self.menuCrystals.addAction(self.actionCircle_Cheetah_peaks)
        self.menuView.addAction(self.actionAutoscale)
        self.menuView.addAction(self.actionHistogram_clip)
        self.menuView.addAction(self.actionAuto_scale_levels)
        self.menuView.addAction(self.menu_view_photonconversion)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuColours.menuAction())
        self.menuBar.addAction(self.menuCrystals.menuAction())
        self.menuBar.addAction(self.menuCXI.menuAction())
        self.menuBar.addAction(self.menuAnalysis.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.refreshfilesPushButton.setText(_translate("MainWindow", "Refresh files", None))
        self.previousPushButton.setText(_translate("MainWindow", "Previous", None))
        self.nextPushButton.setText(_translate("MainWindow", "Next ", None))
        self.playPushButton.setText(_translate("MainWindow", "Play", None))
        self.randomPushButton.setText(_translate("MainWindow", "Random", None))
        self.shufflePushButton.setText(_translate("MainWindow", "Shuffle", None))
        self.jumpToLabel.setText(_translate("MainWindow", "Frame", None))
        self.statusBar.setText(_translate("MainWindow", "Last clicked pixel:     x: -     y: -     value: -     resolution: -", None))
        self.foundPeaksCheckBox.setText(_translate("MainWindow", "Found peaks", None))
        self.predictedPeaksCheckBox.setText(_translate("MainWindow", "Predicted peaks", None))
        self.masksCheckBox.setText(_translate("MainWindow", "Pixel masks", None))
        self.resolutionCheckBox.setText(_translate("MainWindow", "Resolution rings", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuColours.setTitle(_translate("MainWindow", "Colours", None))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis", None))
        self.menuCXI.setTitle(_translate("MainWindow", "Particles", None))
        self.menuCrystals.setTitle(_translate("MainWindow", "Crystals", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.actionSave_data.setText(_translate("MainWindow", "Save data", None))
        self.actionSave_image.setText(_translate("MainWindow", "Save image", None))
        self.actionLoad_geometry.setText(_translate("MainWindow", "Load geometry", None))
        self.actionRefresh_file_list.setText(_translate("MainWindow", "Refresh file list", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionDefault_crystal_display_settings.setText(_translate("MainWindow", "Default crystal display settings", None))
        self.actionCircle_Cheetah_peaks.setText(_translate("MainWindow", "Circle Cheetah peaks", None))
        self.actionDefault_particle_display_settings.setText(_translate("MainWindow", "Default particle display settings", None))
        self.actionHistogram_clip.setText(_translate("MainWindow", "Histogram clip", None))
        self.actionAuto_scale_levels.setText(_translate("MainWindow", "Lock histogram scale", None))
        self.actionAutoscale.setText(_translate("MainWindow", "Auto-scale image", None))
        self.menu_view_photonconversion.setText(_translate("MainWindow", "Photon count conversion", None))

from pyqtgraph import ImageView
