#!/bin/bash

# you should only need to modify the following three lines (?)
export INSTALLDIR=/reg/neh/home/rkirian/local
export HDF5DIR=/reg/neh/home/rkirian/local
export CHEETAHDIR=/reg/neh/home/rkirian/software/cheetah

# 
export LD_LIBRARY_PATH="$INSTALLDIR/lib:$HDF5DIR/lib"
export LD_LIBRARY_PATH="$CHEETAHDIR/source/lcls/myana/release/build/pdsdata/lib/x86_64-linux:$LD_LIBRARY_PATH"
export LD_RUN_PATH=$LD_LIBRARY_PATH

# build cheetah
cd $CHEETAHDIR/source
make clean
make cheetah

# now "install" cheetah...
cp cheetah $INSTALLDIR/bin
