#!/bin/bash
cd $H5DIR
for (( i=1; i<=$#; i++ )); do
    eval RUN=\$$i
    echo "Processing $RUN"
    mkdir $RUN
    cp cheetah.ini $RUN/
    cp psana.cfg $RUN/
    echo "#!/bin/bash\n" > $RUN/process.sh
    echo "psana -n 500 -c psana.cfg  $XTCDIR/*$RUN*.xtc" > $RUN/process.sh
    chmod u+x $RUN/process.sh
    cd $RUN
    ./process.sh
    cd ..
    echo "Exit from processing $RUN"
done