#!/bin/bash
if [ $# -eq 0 ];
then
    echo "USAGE: run_cheetah rXXXX [rYYYY, rZZZZ, ...]"
    echo "The following enviromnmental variables need to be defined: XTCDIR, CONFDIR and H5DIR"
else
    cd $H5DIR
    for (( i=1; i<=$#; i++ )); do
	eval RUN=\${$i}
	echo "Preparing to process $RUN"
	eval RUNDIR=$RUN"_"$(date -d "today" +"%Y%m%d_%H%M%S")
	echo "Creating directory: "$RUNDIR
	mkdir $RUNDIR
	if [ -f $CONFDIR/cheetah_$RUN.ini ];
	then
	    cp $CONFDIR/cheetah_$RUN.ini $RUNDIR/cheetah.ini
	else
	    cp $CONFDIR/cheetah.ini $RUNDIR/
	fi
	if [ -f $CONFDIR/psana_$RUN.cfg ];
	then
	    cp $CONFDIR/psana_$RUN.cfg $RUNDIR/psana.cfg
	else
	    cp $CONFDIR/psana.cfg $RUNDIR/
	fi
	echo "#!/bin/bash\n" > $RUNDIR/process.sh
	echo "psana -c psana.cfg  $XTCDIR/*$RUN*.xtc" > $RUNDIR/process.sh
	chmod u+x $RUNDIR/process.sh
	cd $RUNDIR
	./process.sh
	cd ..
	echo "Setting link from $RUN to directory $RUNDIR"
	rm $RUN
	ln -s $RUNDIR $RUN
	echo "Exit from processing $RUN"
    done
fi
