#!/bin/bash
if [ $# -eq 0 ];
then
    echo "USAGE: submit_cheetah rXXXX [rYYYY, rZZZZ, ...]"
    echo "The following enviromnmental variables need to be defined: XTCDIR, CONFDIR and H5DIR"
else
    cd $H5DIR
    for (( i=1; i<=$#; i++ )); do
	eval RUN=\$$i
	echo "Initializing directory for $RUN"
	mkdir $RUN
	if [ -f $CONFDIR/cheetah_$RUN.ini ];
	then
	    cp $CONFDIR/cheetah_$RUN.ini $RUN/cheetah.ini
	else
	    cp $CONFDIR/cheetah.ini $RUN/
	fi
	if [ -f $CONFDIR/psana_$RUN.cfg ];
	then
	    cp $CONFDIR/psana_$RUN.cfg $RUN/psana.cfg
	else
	    cp $CONFDIR/psana.cfg $RUN/
	fi
	cd $RUN
	echo "#!/bin/bash" > process.sh
	echo "#SBATCH --job-name=Cth$RUN" >> process.sh
	echo "#SBATCH -N1" >> process.sh
	echo "#SBATCH -n20" >> process.sh
	echo "cd $H5DIR/$RUN" >> process.sh
	echo "psana -c psana.cfg  $XTCDIR/*$RUN*.xtc > cheetah_messages.txt" >> process.sh
	sbatch process.sh
	echo "Cheetah job submitted for $RUN"
	cd ..
    done
fi
