# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cheetahgui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(863, 855)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.button_refresh = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_refresh.sizePolicy().hasHeightForWidth())
        self.button_refresh.setSizePolicy(sizePolicy)
        self.button_refresh.setMaximumSize(QtCore.QSize(100, 32))
        self.button_refresh.setObjectName(_fromUtf8("button_refresh"))
        self.horizontalLayout.addWidget(self.button_refresh)
        self.button_view = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_view.sizePolicy().hasHeightForWidth())
        self.button_view.setSizePolicy(sizePolicy)
        self.button_view.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_view.setObjectName(_fromUtf8("button_view"))
        self.horizontalLayout.addWidget(self.button_view)
        self.button_runCheetah = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_runCheetah.sizePolicy().hasHeightForWidth())
        self.button_runCheetah.setSizePolicy(sizePolicy)
        self.button_runCheetah.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_runCheetah.setObjectName(_fromUtf8("button_runCheetah"))
        self.horizontalLayout.addWidget(self.button_runCheetah)
        self.button_index = QtGui.QPushButton(self.centralwidget)
        self.button_index.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_index.sizePolicy().hasHeightForWidth())
        self.button_index.setSizePolicy(sizePolicy)
        self.button_index.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_index.setObjectName(_fromUtf8("button_index"))
        self.horizontalLayout.addWidget(self.button_index)
        self.button_viewhits = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_viewhits.sizePolicy().hasHeightForWidth())
        self.button_viewhits.setSizePolicy(sizePolicy)
        self.button_viewhits.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_viewhits.setObjectName(_fromUtf8("button_viewhits"))
        self.horizontalLayout.addWidget(self.button_viewhits)
        self.button_virtualpowder = QtGui.QPushButton(self.centralwidget)
        self.button_virtualpowder.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_virtualpowder.sizePolicy().hasHeightForWidth())
        self.button_virtualpowder.setSizePolicy(sizePolicy)
        self.button_virtualpowder.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_virtualpowder.setObjectName(_fromUtf8("button_virtualpowder"))
        self.horizontalLayout.addWidget(self.button_virtualpowder)
        self.button_virtualpowder_3 = QtGui.QPushButton(self.centralwidget)
        self.button_virtualpowder_3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_virtualpowder_3.sizePolicy().hasHeightForWidth())
        self.button_virtualpowder_3.setSizePolicy(sizePolicy)
        self.button_virtualpowder_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_virtualpowder_3.setObjectName(_fromUtf8("button_virtualpowder_3"))
        self.horizontalLayout.addWidget(self.button_virtualpowder_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout2 = QtGui.QHBoxLayout()
        self.horizontalLayout2.setObjectName(_fromUtf8("horizontalLayout2"))
        self.TabWidget = QtGui.QTabWidget(self.centralwidget)
        self.TabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.TabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.TabWidget.setObjectName(_fromUtf8("TabWidget"))
        self.tab_status = QtGui.QWidget()
        self.tab_status.setObjectName(_fromUtf8("tab_status"))
        self.table_calibration = QtGui.QTableWidget(self.tab_status)
        self.table_calibration.setGeometry(QtCore.QRect(0, 0, 831, 741))
        self.table_calibration.setObjectName(_fromUtf8("table_calibration"))
        self.table_calibration.setColumnCount(10)
        self.table_calibration.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_calibration.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration.setHorizontalHeaderItem(9, item)
        self.table_calibration.horizontalHeader().setDefaultSectionSize(90)
        self.table_calibration.horizontalHeader().setHighlightSections(False)
        self.TabWidget.addTab(self.tab_status, _fromUtf8(""))
        self.tab_calib = QtGui.QWidget()
        self.tab_calib.setObjectName(_fromUtf8("tab_calib"))
        self.table_calibration_2 = QtGui.QTableWidget(self.tab_calib)
        self.table_calibration_2.setGeometry(QtCore.QRect(0, 0, 831, 741))
        self.table_calibration_2.setObjectName(_fromUtf8("table_calibration_2"))
        self.table_calibration_2.setColumnCount(8)
        self.table_calibration_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_calibration_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table_calibration_2.setHorizontalHeaderItem(7, item)
        self.table_calibration_2.horizontalHeader().setDefaultSectionSize(90)
        self.table_calibration_2.horizontalHeader().setHighlightSections(False)
        self.TabWidget.addTab(self.tab_calib, _fromUtf8(""))
        self.horizontalLayout2.addWidget(self.TabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 863, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuCheetah = QtGui.QMenu(self.menuBar)
        self.menuCheetah.setObjectName(_fromUtf8("menuCheetah"))
        self.menuAnalysis = QtGui.QMenu(self.menuBar)
        self.menuAnalysis.setObjectName(_fromUtf8("menuAnalysis"))
        self.menu_masks = QtGui.QMenu(self.menuBar)
        self.menu_masks.setObjectName(_fromUtf8("menu_masks"))
        self.menuPowder = QtGui.QMenu(self.menuBar)
        self.menuPowder.setObjectName(_fromUtf8("menuPowder"))
        self.menuLogs = QtGui.QMenu(self.menuBar)
        self.menuLogs.setObjectName(_fromUtf8("menuLogs"))
        MainWindow.setMenuBar(self.menuBar)
        self.menu_file_autorefresh = QtGui.QAction(MainWindow)
        self.menu_file_autorefresh.setObjectName(_fromUtf8("menu_file_autorefresh"))
        self.menu_file_refreshtable = QtGui.QAction(MainWindow)
        self.menu_file_refreshtable.setObjectName(_fromUtf8("menu_file_refreshtable"))
        self.menu_file_startcrawler = QtGui.QAction(MainWindow)
        self.menu_file_startcrawler.setObjectName(_fromUtf8("menu_file_startcrawler"))
        self.menu_file_command = QtGui.QAction(MainWindow)
        self.menu_file_command.setObjectName(_fromUtf8("menu_file_command"))
        self.menu_file_quit = QtGui.QAction(MainWindow)
        self.menu_file_quit.setObjectName(_fromUtf8("menu_file_quit"))
        self.menu_mask_badpixdark = QtGui.QAction(MainWindow)
        self.menu_mask_badpixdark.setObjectName(_fromUtf8("menu_mask_badpixdark"))
        self.menu_mask_badpixbright = QtGui.QAction(MainWindow)
        self.menu_mask_badpixbright.setObjectName(_fromUtf8("menu_mask_badpixbright"))
        self.actionDefault_particle_display_settings = QtGui.QAction(MainWindow)
        self.actionDefault_particle_display_settings.setObjectName(_fromUtf8("actionDefault_particle_display_settings"))
        self.actionHistogram_clip = QtGui.QAction(MainWindow)
        self.actionHistogram_clip.setCheckable(True)
        self.actionHistogram_clip.setChecked(True)
        self.actionHistogram_clip.setObjectName(_fromUtf8("actionHistogram_clip"))
        self.actionAuto_scale_levels = QtGui.QAction(MainWindow)
        self.actionAuto_scale_levels.setCheckable(True)
        self.actionAuto_scale_levels.setChecked(True)
        self.actionAuto_scale_levels.setObjectName(_fromUtf8("actionAuto_scale_levels"))
        self.menu_cheetah_processselected = QtGui.QAction(MainWindow)
        self.menu_cheetah_processselected.setObjectName(_fromUtf8("menu_cheetah_processselected"))
        self.menu_cheetah_relabel = QtGui.QAction(MainWindow)
        self.menu_cheetah_relabel.setObjectName(_fromUtf8("menu_cheetah_relabel"))
        self.menu_cheetah_autorun = QtGui.QAction(MainWindow)
        self.menu_cheetah_autorun.setObjectName(_fromUtf8("menu_cheetah_autorun"))
        self.menu_mask_combine = QtGui.QAction(MainWindow)
        self.menu_mask_combine.setObjectName(_fromUtf8("menu_mask_combine"))
        self.menu_mask_makecspadgain = QtGui.QAction(MainWindow)
        self.menu_mask_makecspadgain.setObjectName(_fromUtf8("menu_mask_makecspadgain"))
        self.menu_mask_translatecspadgain = QtGui.QAction(MainWindow)
        self.menu_mask_translatecspadgain.setObjectName(_fromUtf8("menu_mask_translatecspadgain"))
        self.actionPeakogram = QtGui.QAction(MainWindow)
        self.actionPeakogram.setObjectName(_fromUtf8("actionPeakogram"))
        self.actionSaturation_check = QtGui.QAction(MainWindow)
        self.actionSaturation_check.setObjectName(_fromUtf8("actionSaturation_check"))
        self.actionHit_rate_plot = QtGui.QAction(MainWindow)
        self.actionHit_rate_plot.setObjectName(_fromUtf8("actionHit_rate_plot"))
        self.actionResolution_plot = QtGui.QAction(MainWindow)
        self.actionResolution_plot.setObjectName(_fromUtf8("actionResolution_plot"))
        self.actionPowderHits1 = QtGui.QAction(MainWindow)
        self.actionPowderHits1.setObjectName(_fromUtf8("actionPowderHits1"))
        self.actionVirtual_powder_hits_class_1_detector_corrected_only = QtGui.QAction(MainWindow)
        self.actionVirtual_powder_hits_class_1_detector_corrected_only.setObjectName(_fromUtf8("actionVirtual_powder_hits_class_1_detector_corrected_only"))
        self.actionVirtual_powder_blanks_class_0_background_subtracted = QtGui.QAction(MainWindow)
        self.actionVirtual_powder_blanks_class_0_background_subtracted.setObjectName(_fromUtf8("actionVirtual_powder_blanks_class_0_background_subtracted"))
        self.actionVirtual_powder_blanks_class_0_detector_corrected_only = QtGui.QAction(MainWindow)
        self.actionVirtual_powder_blanks_class_0_detector_corrected_only.setObjectName(_fromUtf8("actionVirtual_powder_blanks_class_0_detector_corrected_only"))
        self.actionPeakfinder_virtual_powder_hits_class_1 = QtGui.QAction(MainWindow)
        self.actionPeakfinder_virtual_powder_hits_class_1.setObjectName(_fromUtf8("actionPeakfinder_virtual_powder_hits_class_1"))
        self.actionPeakfinder_virtual_powder_blanks_class_0 = QtGui.QAction(MainWindow)
        self.actionPeakfinder_virtual_powder_blanks_class_0.setObjectName(_fromUtf8("actionPeakfinder_virtual_powder_blanks_class_0"))
        self.actionBatch_log_file = QtGui.QAction(MainWindow)
        self.actionBatch_log_file.setObjectName(_fromUtf8("actionBatch_log_file"))
        self.actionCheetah_log_file = QtGui.QAction(MainWindow)
        self.actionCheetah_log_file.setObjectName(_fromUtf8("actionCheetah_log_file"))
        self.actionCheetah_status_file = QtGui.QAction(MainWindow)
        self.actionCheetah_status_file.setObjectName(_fromUtf8("actionCheetah_status_file"))
        self.menuFile.addAction(self.menu_file_command)
        self.menuFile.addAction(self.menu_file_startcrawler)
        self.menuFile.addAction(self.menu_file_refreshtable)
        self.menuFile.addAction(self.menu_file_autorefresh)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menu_file_quit)
        self.menuCheetah.addAction(self.menu_cheetah_processselected)
        self.menuCheetah.addAction(self.menu_cheetah_relabel)
        self.menuCheetah.addAction(self.menu_cheetah_autorun)
        self.menuAnalysis.addAction(self.actionHit_rate_plot)
        self.menuAnalysis.addAction(self.actionResolution_plot)
        self.menuAnalysis.addAction(self.actionSaturation_check)
        self.menuAnalysis.addAction(self.actionPeakogram)
        self.menu_masks.addAction(self.menu_mask_badpixdark)
        self.menu_masks.addAction(self.menu_mask_badpixbright)
        self.menu_masks.addAction(self.menu_mask_combine)
        self.menu_masks.addAction(self.menu_mask_makecspadgain)
        self.menu_masks.addAction(self.menu_mask_translatecspadgain)
        self.menuPowder.addAction(self.actionPowderHits1)
        self.menuPowder.addAction(self.actionVirtual_powder_hits_class_1_detector_corrected_only)
        self.menuPowder.addAction(self.actionVirtual_powder_blanks_class_0_background_subtracted)
        self.menuPowder.addAction(self.actionVirtual_powder_blanks_class_0_detector_corrected_only)
        self.menuPowder.addAction(self.actionPeakfinder_virtual_powder_hits_class_1)
        self.menuPowder.addAction(self.actionPeakfinder_virtual_powder_blanks_class_0)
        self.menuLogs.addAction(self.actionBatch_log_file)
        self.menuLogs.addAction(self.actionCheetah_log_file)
        self.menuLogs.addAction(self.actionCheetah_status_file)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuCheetah.menuAction())
        self.menuBar.addAction(self.menu_masks.menuAction())
        self.menuBar.addAction(self.menuAnalysis.menuAction())
        self.menuBar.addAction(self.menuPowder.menuAction())
        self.menuBar.addAction(self.menuLogs.menuAction())

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.button_refresh.setText(_translate("MainWindow", "Refresh", None))
        self.button_view.setText(_translate("MainWindow", "Dataset view", None))
        self.button_runCheetah.setText(_translate("MainWindow", "Run Cheetah", None))
        self.button_index.setText(_translate("MainWindow", "Turbo index", None))
        self.button_viewhits.setText(_translate("MainWindow", "View hits", None))
        self.button_virtualpowder.setText(_translate("MainWindow", "Virtual powder", None))
        self.button_virtualpowder_3.setText(_translate("MainWindow", "Peakogram", None))
        item = self.table_calibration.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Run", None))
        item = self.table_calibration.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dataset", None))
        item = self.table_calibration.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "XTC", None))
        item = self.table_calibration.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cheetah", None))
        item = self.table_calibration.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CrystFEL", None))
        item = self.table_calibration.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "H5 Directory", None))
        item = self.table_calibration.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Nprocessed", None))
        item = self.table_calibration.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Nhits", None))
        item = self.table_calibration.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Nindex", None))
        item = self.table_calibration.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Hitrate%", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab_status), _translate("MainWindow", "Processing status", None))
        item = self.table_calibration_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Run", None))
        item = self.table_calibration_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dataset", None))
        item = self.table_calibration_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "cheetah.ini", None))
        item = self.table_calibration_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Darkcal", None))
        item = self.table_calibration_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gaincal", None))
        item = self.table_calibration_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Geometry", None))
        item = self.table_calibration_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Badpixmask", None))
        item = self.table_calibration_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Peakmask", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab_calib), _translate("MainWindow", "Calibration manager", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuCheetah.setTitle(_translate("MainWindow", "Cheetah", None))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis", None))
        self.menu_masks.setTitle(_translate("MainWindow", "Masks", None))
        self.menuPowder.setTitle(_translate("MainWindow", "Powder", None))
        self.menuLogs.setTitle(_translate("MainWindow", "Logs", None))
        self.menu_file_autorefresh.setText(_translate("MainWindow", "Auto refresh table", None))
        self.menu_file_refreshtable.setText(_translate("MainWindow", "Refresh table", None))
        self.menu_file_startcrawler.setText(_translate("MainWindow", "Start crawler", None))
        self.menu_file_command.setText(_translate("MainWindow", "Unlock command operations", None))
        self.menu_file_quit.setText(_translate("MainWindow", "Quit", None))
        self.menu_mask_badpixdark.setText(_translate("MainWindow", "Make bad pixel mask from darkcal", None))
        self.menu_mask_badpixbright.setText(_translate("MainWindow", "Make bad pixel mask from brightfield", None))
        self.actionDefault_particle_display_settings.setText(_translate("MainWindow", "Default particle display settings", None))
        self.actionHistogram_clip.setText(_translate("MainWindow", "Histogram clip", None))
        self.actionAuto_scale_levels.setText(_translate("MainWindow", "Clamp histogram scale ", None))
        self.menu_cheetah_processselected.setText(_translate("MainWindow", "Process selected runs", None))
        self.menu_cheetah_relabel.setText(_translate("MainWindow", "Label or relable dataset", None))
        self.menu_cheetah_autorun.setText(_translate("MainWindow", "Autorun when new data is ready", None))
        self.menu_mask_combine.setText(_translate("MainWindow", "Combine masks", None))
        self.menu_mask_makecspadgain.setText(_translate("MainWindow", "Create CSPAD gain map", None))
        self.menu_mask_translatecspadgain.setText(_translate("MainWindow", "Translate CSPAD gain map", None))
        self.actionPeakogram.setText(_translate("MainWindow", "Peakogram", None))
        self.actionSaturation_check.setText(_translate("MainWindow", "Saturation check", None))
        self.actionHit_rate_plot.setText(_translate("MainWindow", "Hit rate plot", None))
        self.actionResolution_plot.setText(_translate("MainWindow", "Resolution plot", None))
        self.actionPowderHits1.setText(_translate("MainWindow", "Virtual powder hits (class 1, background subtracted)", None))
        self.actionVirtual_powder_hits_class_1_detector_corrected_only.setText(_translate("MainWindow", "Virtual powder hits (class 1, detector corrected only)", None))
        self.actionVirtual_powder_blanks_class_0_background_subtracted.setText(_translate("MainWindow", "Virtual powder blanks (class 0, background subtracted)", None))
        self.actionVirtual_powder_blanks_class_0_detector_corrected_only.setText(_translate("MainWindow", "Virtual powder blanks (class 0, detector corrected only)", None))
        self.actionPeakfinder_virtual_powder_hits_class_1.setText(_translate("MainWindow", "Peakfinder virtual powder hits (class 1)", None))
        self.actionPeakfinder_virtual_powder_blanks_class_0.setText(_translate("MainWindow", "Peakfinder virtual powder blanks (class 0)", None))
        self.actionBatch_log_file.setText(_translate("MainWindow", "Batch log file", None))
        self.actionCheetah_log_file.setText(_translate("MainWindow", "Cheetah log file", None))
        self.actionCheetah_status_file.setText(_translate("MainWindow", "Cheetah status file", None))

