#!/bin/tcsh


switch ($1)

    case cfelsgi:
    rsync -av --exclude 'build' --exclude '.git' . barty@cfelsgi.desy.de:local/c/cheetah/
    breaksw

    case cfelsgi-test:
    rsync -av --exclude 'build' --exclude '.git' . barty@cfelsgi.desy.de:local/c/cheetah-test/
    breaksw
    
    case psexport:
    rsync -av --exclude 'build' --exclude 'lcls' --exclude '.git' --exclude 'lcls.old.20120504' --exclude '*.tar' . barty@psexport.slac.stanford.edu:c/cheetah/
    #rsync -av --exclude 'build' --exclude '.git' --exclude 'lcls.old.20120504' --exclude '*.tar' . barty@psexport.slac.stanford.edu:c/cheetah/
    #rsync -av *.cpp *.h  barty@psexport.slac.stanford.edu:c/cheetah/
    #rsync -av --exclude 'release' --exclude 'build' --exclude '.git' --exclude '*.o' --exclude Makefile . barty@psexport.slac.stanford.edu:c/cheetah/

endsw
