#!/bin/bash

export CHEETAHDIR=$HOME/cheetah/	# CHEETAH DIRECTORY
export XTCDIR=/reg/d/ana12/cxi/cxi54312/scratch/yoon82	# XTC DIRECTORY
export H5DIR=/reg/d/ana12/cxi/cxi54312/scratch/yoon82	# IT WILL SAVE HERE
export CONFIGDIR=/reg/d/psdm/cxi/cxi54312/scratch/cheetah # CONFIG DIRECTORY (OPTIONAL)
export CHEETAH=$CHEETAHDIR/source/cheetah # CHEETAH EXECUTABLE
export LD_LIBRARY_PATH=$CHEETAHDIR/source/lcls-psana/build/x86_64-rhel5-gcc41-opt/chuck_ana_pkg:$LD_LIBRARY_PATH # PSANA
export LD_LIBRARY_PATH=$CHEETAHDIR/source/lcls-psana/build/x86_64-rhel5-gcc41-opt/cheetah_ana_pkg:$LD_LIBRARY_PATH # PSANA

./hitfinder -r 1 -t debug -i cheetah.ini -O -p	# -p for PSANA CHEETAH

