#!/bin/tcsh

# Script for simplifying the conversion of XTC files to HDF5
#	Syntax:
#	> crystfinder r0003 crystfinder.ini
#

#########################################################
# CUSTOMIZE FOR YOUR OWN USE

setenv XTCDIR '/reg/d/psdm/cxi/cxi54312/xtc'
setenv H5DIR '/reg/neh/home/yoon82/cheetah/hdf5'
setenv LOGDIR '/reg/neh/home/yoon82/cheetah/hdf5/logs'
setenv INIDIR '/reg/neh/home/yoon82/cheetah/analysis-rel'
setenv COMMAND 'psana'
setenv myXTC 'e187-r0035-s00-c00.xtc'
setenv myTag 'chuckTag'

#########################################################

setenv LD_LIBRARY_PATH /reg/neh/home/yoon82/cheetah/analysis-rel/arch/x86_64-rhel5-gcc41-opt/lib:$LD_LIBRARY_PATH
setenv LD_LIBRARY_PATH /reg/g/psdm/sw/releases/ana-current/arch/x86_64-rhel5-gcc41-opt/lib:$LD_LIBRARY_PATH

setenv LD_LIBRARY_PATH /reg/neh/home/yoon82/hdf5/lib:$LD_LIBRARY_PATH

# All OK?
echo $1
echo $2

setenv savedir "$H5DIR/$1-$myTag"

# Has an '.ini' file been specified on the commanbd line?
if ($2 != '') then
	setenv INIFILE $2
else
	setenv INIFILE 'cheetah.ini'
endif


# Create directory for this data set
echo 'Creating directory'
if( ! -e $savedir) then
	mkdir $savedir
endif

# Move to HDF5 directory
cd $savedir

# Clean out old HDF5 files
echo 'Removing existing HDF5 files'
rm -f *.h5

# Create configuration files
echo 'Creating configuration files'
cp $INIDIR/$INIFILE cheetah.ini
cp $INIDIR/psana.cfg psana.cfg
ls $XTCDIR/*$1* > files.txt

# make everything group editable!
chmod -R g+w $savedir

# Spawn cspad_cryst for file conversion
#echo "$COMMAND -l files.txt >& $LOGDIR/$1.log" 
$COMMAND $XTCDIR/$myXTC #>& $LOGDIR/$1.log 


# make everything group editable!
chmod -R g+w $savedir

#
echo 'crystfinder has finished'
